/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as admins from "../admins.js";
import type * as crons from "../crons.js";
import type * as devices from "../devices.js";
import type * as earnings from "../earnings.js";
import type * as payments from "../payments.js";
import type * as subscriptions from "../subscriptions.js";
import type * as topuptransactions from "../topuptransactions.js";
import type * as users from "../users.js";
import type * as widthrawaltransactions from "../widthrawaltransactions.js";
import type * as wifis from "../wifis.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  admins: typeof admins;
  crons: typeof crons;
  devices: typeof devices;
  earnings: typeof earnings;
  payments: typeof payments;
  subscriptions: typeof subscriptions;
  topuptransactions: typeof topuptransactions;
  users: typeof users;
  widthrawaltransactions: typeof widthrawaltransactions;
  wifis: typeof wifis;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
